package com.example.domain

import com.example.data.local.BotSettingsEntity
import com.example.data.local.FaqEntity

object CodeExporter {

    fun generateFlaskPythonCode(settings: BotSettingsEntity, faqs: List<FaqEntity>): String {
        val systemPrompt = AiSupportEngine.buildSystemPrompt(settings, faqs)
            .replace("\"\"\"", "\\\"\\\"\\\"")

        return """
# ==============================================================================
# WhatsApp Business AI Customer Support Webhook Server
# Generated by WaBot Studio
# ==============================================================================

import os
import requests
from flask import Flask, request, jsonify
from google import genai

app = Flask(__name__)

# --- Environment Credentials ---
VERIFY_TOKEN = os.environ.get("VERIFY_TOKEN", "${settings.verifyToken}")
WA_TOKEN = os.environ.get("WA_TOKEN", "${settings.waToken.ifBlank { "YOUR_META_PERMANENT_ACCESS_TOKEN" }}")
PHONE_ID = os.environ.get("PHONE_ID", "${settings.phoneId}")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

# Initialize AI Client
ai = genai.Client(api_key=GEMINI_API_KEY)

# --- Business System Prompt ---
SYSTEM = \"\"\"${systemPrompt}\"\"\"

@app.route("/", methods=["GET"])
def health():
    return jsonify({
        "status": "online",
        "bot": "${settings.businessName}",
        "engine": "Gemini 3.5 Flash",
        "version": "1.0.0"
    }), 200

@app.route("/webhook", methods=["GET"])
def verify():
    # Meta Webhook Verification Handshake
    mode = request.args.get("hub.mode")
    token = request.args.get("hub.verify_token")
    challenge = request.args.get("hub.challenge")

    if mode == "subscribe" and token == VERIFY_TOKEN:
        print("Webhook verified successfully by Meta!")
        return challenge, 200
    print(f"Webhook verification failed: token={token}")
    return "forbidden", 403

@app.route("/webhook", methods=["POST"])
def incoming():
    data = request.get_json(silent=True)
    if not data:
        return "bad request", 400

    try:
        entry = data.get("entry", [])[0]
        change = entry.get("changes", [])[0]
        value = change.get("value", {})
        messages = value.get("messages", [])

        if not messages:
            return "ok", 200

        msg = messages[0]
        if msg.get("type") == "text":
            customer_number = msg.get("from")
            incoming_text = msg.get("text", {}).get("body", "")

            print(f"Incoming WhatsApp message from {customer_number}: '{incoming_text}'")

            # Call Gemini AI with Roman Urdu / English bilingual prompt
            response = ai.models.generate_content(
                model="gemini-2.5-flash",
                contents=incoming_text,
                config={
                    "system_instruction": SYSTEM,
                    "temperature": 0.35,
                    "max_output_tokens": 300,
                }
            )
            reply = response.text.strip() if response.text else "${settings.humanEscalationMessage}"

            print(f"Generated AI reply: '{reply}'")

            # Outbound WhatsApp Cloud API POST
            wa_url = f"https://graph.facebook.com/v21.0/{PHONE_ID}/messages"
            headers = {
                "Authorization": f"Bearer {WA_TOKEN}",
                "Content-Type": "application/json"
            }
            payload = {
                "messaging_product": "whatsapp",
                "recipient_type": "individual",
                "to": customer_number,
                "type": "text",
                "text": {"body": reply}
            }

            resp = requests.post(wa_url, headers=headers, json=payload, timeout=10)
            print(f"WhatsApp API Status: {resp.status_code}")

    except Exception as e:
        print(f"Error processing webhook: {e}")

    return "ok", 200

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
        """.trimIndent()
    }

    fun generateRequirementsTxt(): String {
        return """
flask==3.0.3
requests==2.32.3
google-genai==0.3.0
gunicorn==22.0.0
        """.trimIndent()
    }

    fun generateEnvFile(settings: BotSettingsEntity): String {
        return """
VERIFY_TOKEN=${settings.verifyToken}
WA_TOKEN=${settings.waToken.ifBlank { "EAAG...MetaAccessToken" }}
PHONE_ID=${settings.phoneId}
GEMINI_API_KEY=YOUR_GEMINI_API_KEY
PORT=5000
        """.trimIndent()
    }

    fun generateDockerfile(): String {
        return """
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "app:app"]
        """.trimIndent()
    }
}
